export const personArr = () => [
  {
    titleUrl: 'img/text-刻晴.png',
    coverUrl: 'img/刻晴.jpg',
    bgUrl: 'img/璃月.jpg',
    artUrl: 'img/刻晴big.png',
    elementUrl: 'img/元素-雷.png',
    cv: '谢莹',
  },
  {
    titleUrl: 'img/text-宵宫.png',
    coverUrl: 'img/宵宫.jpg',
    bgUrl: 'img/稻妻.jpg',
    artUrl: 'img/宵宫big.png',
    elementUrl: 'img/元素-火.png',
    cv: '金娜',
  },
  {
    titleUrl: 'img/text-神子.png',
    coverUrl: 'img/神子.jpg',
    bgUrl: 'img/稻妻.jpg',
    artUrl: 'img/神子big.png',
    elementUrl: 'img/元素-雷.png',
    cv: '杜冥鸦',
  },
  {
    titleUrl: 'img/text-胡桃.png',
    coverUrl: 'img/胡桃.jpg',
    bgUrl: 'img/稻妻.jpg',
    artUrl: 'img/胡桃big.png',
    elementUrl: 'img/元素-火.png',
    cv: '陶典',
  },
  {
    titleUrl: 'img/text-妮露.png',
    coverUrl: 'img/妮露.jpg',
    bgUrl: 'img/须弥.jpg',
    artUrl: 'img/妮露big.png',
    elementUrl: 'img/元素-水.png',
    cv: '紫苏九月',
  },
  {
    titleUrl: 'img/text-心海.png',
    coverUrl: 'img/心海.jpg',
    bgUrl: 'img/稻妻.jpg',
    artUrl: 'img/心海big.png',
    elementUrl: 'img/元素-水.png',
    cv: '龟娘',
  },
  {
    titleUrl: 'img/text-凌华.png',
    coverUrl: 'img/凌华.jpg',
    bgUrl: 'img/稻妻.jpg',
    artUrl: 'img/凌华big.png',
    elementUrl: 'img/元素-冰.png',
    cv: '小N',
  },
  {
    titleUrl: 'img/text-将军.png',
    coverUrl: 'img/将军.jpg',
    bgUrl: 'img/稻妻.jpg',
    artUrl: 'img/将军big.png',
    elementUrl: 'img/元素-雷.png',
    cv: '菊花花',
  },
];
